protected/models/Formulario.php
<?php

/**
 * This is the model class for table "formulario".
 *
 * The followings are the available columns in table 'formulario':
 * @property string $id
 * @property string $nombres
 * @property string $apellidos
 * @property string $telefono
 * @property string $fecha_nacimiento
 * @property integer $user_id
 *
 * The followings are the available model relations:
 * @property FotoUsuario $fotosUsuario
 * @property User $user
 */
class Formulario extends CActiveRecord
{
	public $usuario;
	public $clave;
	public $fotos;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'formulario';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('nombres, apellidos, telefono, fecha_nacimiento,  user_id, usuario, clave', 'required'),
			array('user_id', 'numerical', 'integerOnly'=>true),
			array('nombres, apellidos', 'length', 'max'=>100),
			array('telefono', 'length', 'max'=>20),
			array('fecha_nacimiento', 'length', 'max'=>255),
			array('fotos','safe'),
			array('usuario','email'),

			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, nombres, apellidos, telefono, fecha_nacimiento,  user_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'nombres' => 'Nombres',
			'apellidos' => 'Apellidos',
			'telefono' => 'Telefono',
			'fecha_nacimiento' => 'Fecha Nacimiento',
			'fotos_usuario' => 'Fotos Usuario',
			'user_id' => 'User',
			'usuario' => 'Usuario (correo)',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('nombres',$this->nombres,true);
		$criteria->compare('apellidos',$this->apellidos,true);
		$criteria->compare('telefono',$this->telefono,true);
		$criteria->compare('fecha_nacimiento',$this->fecha_nacimiento,true);
		$criteria->compare('user_id',$this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Formulario the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function myFileReceptor($fullFileName,$userdata) 
	{
        // userdata is the same passed via widget config.

    }
}

protected/controllers/FormularioController.php
<?php

class FormularioController extends Controller
{
	/**
	* @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	* using two-column layout. See 'protected/views/layouts/column2.php'.
	*/
	public $layout='//layouts/column2';

	/**
	* @return array action filters
	*/
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	* Specifies the access control rules.
	* This method is used by the 'accessControl' filter.
	* @return array access control rules
	*/
	public function accessRules()
	{
		return array(
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions' => array('admin', 'create', 'index', 'view', 'delete', 'update','upload'),
                'expression' => 'Yii::app()->user->checkAccess("Admin1")',
            ),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionUpload()
	{
	 
        Yii::import("ext.EAjaxUpload.qqFileUploader");
 
        $folder=Yii::getPathOfAlias('webroot').'/fotos/';// folder for uploaded files
        $allowedExtensions = array("jpg","jpeg","gif","png");//array("jpg","jpeg","gif","exe","mov" and etc...
        $sizeLimit = 100 * 1024 * 1024;// maximum file size in bytes
        $uploader  = new qqFileUploader($allowedExtensions, $sizeLimit);
        $result    = $uploader->handleUpload($folder);
        $return    = htmlspecialchars(json_encode($result), ENT_NOQUOTES);
 
        $fileSize  = filesize($folder.$result['filename']);//GETTING FILE SIZE
        $fileName  = $result['filename'];//GETTING FILE NAME
        //$img = CUploadedFile::getInstance($model,'image');
 
        echo $return;// it's array
	}

	/**
	* Displays a particular model.
	* @param integer $id the ID of the model to be displayed
	*/
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	* Creates a new model.
	* If creation is successful, the browser will be redirected to the 'view' page.
	*/
	public function actionCreate()
	{
		$model=new Formulario;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Formulario']))
		{
			$model->attributes=$_POST['Formulario'];
			$login = $model->usuario;
			$clave   = md5($model->clave);
			$usu     = new User;
			$usu->nombre = $model->nombres;
			$usu->password = $clave;
			$usu->username = $login;
			$usu->save();
			
			$command = Yii::app()->db->createCommand();
			$command->insert('AuthAssignment', array(
			    'itemname'=>'usuario',
			    'userid'=>$login,
			));

			$model->user_id = $usu->id;
			if($model->save())
			{
				$fotos   = explode(',',$model->fotos);
				for($i = 0; $i<count($fotos); $i++)
				{
					$fotoUsu = new FotoUsuario;
					$fotoUsu->formulario_id = $model->id;
					$fotoUsu->nombre_foto = $fotos[$i];
					$fotoUsu->direccion_foto = Yii::getPathOfAlias('webroot').'/fotos/'.$fotos[$i];
					$fotoUsu->save();

				}
				 $this->mailsend($model->usuario,'juan.cortes.c@gmail.com','envio de correos','ha sido creado el usuario');
				$this->redirect(array('view','id'=>$model->id));
				 
			}
		}

		$this->render('create',array(
		'model'=>$model,
		));
	}

	private function mailsend($to,$from,$subject,$message)
	{
        $mail=Yii::app()->Smtpmail;
        $mail->SetFrom($from, 'From NAme');
        $mail->Subject    = $subject;
        $mail->MsgHTML($message);
        $mail->AddAddress($to, "");
        if(!$mail->Send()) {
            echo "Mailer Error: " . $mail->ErrorInfo;
        }else {
            echo "Message sent!";
        }
        $mail->ClearAddresses(); //clear addresses for next email sending
    }

	/**
	* Updates a particular model.
	* If update is successful, the browser will be redirected to the 'view' page.
	* @param integer $id the ID of the model to be updated
	*/
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Formulario']))
		{
			$model->attributes=$_POST['Formulario'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	* Deletes a particular model.
	* If deletion is successful, the browser will be redirected to the 'admin' page.
	* @param integer $id the ID of the model to be deleted
	*/
	public function actionDelete($id)
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel($id)->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	* Lists all models.
	*/
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Formulario');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	* Manages all models.
	*/
	public function actionAdmin()
	{
		$model=new Formulario('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Formulario']))
			$model->attributes=$_GET['Formulario'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	* Returns the data model based on the primary key given in the GET variable.
	* If the data model is not found, an HTTP exception will be raised.
	* @param integer $id the ID of the model to be loaded
	* @return Formulario the loaded model
	* @throws CHttpException
	*/
	public function loadModel($id)
	{
		$model=Formulario::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	* Performs the AJAX validation.
	* @param Formulario $model the model to be validated
	*/
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='formulario-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/formulario/_form.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */
/* @var $form BSActiveForm */
?>

<script type="text/javascript">
    $(function()
    {
        $(".select2").select2({
            width:'resolve'
        });

        $("#fecha_nacimiento").datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 1,
            showOn: "both",//button
            buttonImageOnly: false,
            showAnim: "slideDown",
            dateFormat: "yy-mm-dd",
            
        });
    });

    function guardar()
    {   
        var json = eval("(" + doc + ")");  
        if($("#fotos").val() == "")
            $("#fotos").val(json.filename);
        else
        {
            val = $("#fotos").val();
            $("#fotos").val(val+","+json.filename);
        }

    }
</script>

<?php $form=$this->beginWidget('bootstrap.widgets.BsActiveForm', array(
    'id'=>'formulario-form',
    // Please note: When you enable ajax validation, make sure the corresponding
    // controller action is handling ajax validation correctly.
    // There is a call to performAjaxValidation() commented in generated controller code.
    // See class documentation of CActiveForm for details on this.
    'enableAjaxValidation'=>false,
)); ?>

    <p class="help-block">Los campos con <span class="required">*</span> son obligatorios.</p>

    <?php echo $form->errorSummary($model); ?>

    <?php echo $form->textFieldControlGroup($model,'nombres',array('maxlength'=>100)); ?>
    <?php echo $form->textFieldControlGroup($model,'apellidos',array('maxlength'=>100)); ?>
    <?php echo $form->textFieldControlGroup($model,'telefono',array('maxlength'=>20)); ?>
    <?php echo $form->textFieldControlGroup($model,'fecha_nacimiento',array('id'=>'fecha_nacimiento','maxlength'=>255)); ?>
    <?php echo $form->textFieldControlGroup($model,'fotos',array('id'=>'fotos','maxlength'=>11)); ?>

    <?php
     $this->widget('ext.EAjaxUpload.EAjaxUpload',
    array(
            'id'=>'uploadFile',
            'config'=>array(
                   'action'=>Yii::app()->createUrl('formulario/upload'),
                   'allowedExtensions'=>array("jpg","jpeg","gif","png"),//array("jpg","jpeg","gif","exe","mov" and etc...
                   'sizeLimit'=>1000*1024*1024,// maximum file size in bytes
                   'minSizeLimit'=>1*1024,
                   'auto'=>true,
                   'multiple' => true,
                   'onComplete'=>"js:function(id, fileName, responseJSON){
                             doc = JSON.stringify(responseJSON);
                            guardar();  }",
                   'messages'=>array(
                                     'typeError'=>"{file} has invalid extension. Only {extensions} are allowed.",
                                    'sizeError'=>"{file} is too large, maximum file size is {sizeLimit}.",
                                    'minSizeError'=>"{file} is too small, minimum file size is {minSizeLimit}.",
                                    'emptyError'=>"{file} is empty, please select files again without it.",
                                    'onLeave'=>"The files are being uploaded, if you leave now the upload will be cancelled."
                                   ),
                   'showMessage'=>"js:function(message){ alert(message); }"
                   )
     
                   ));
    ?>


    <?php echo $form->textFieldControlGroup($model,'usuario',array('maxlength'=>150)); ?>
    <?php echo $form->passwordFieldControlGroup($model,'clave',array('maxlength'=>150)); ?>
    <?php //echo $form->dropDownListControlGroup($model, 'user_id', User::model()->getUsers(), array('id' => 'user_id', 'class'=>'select select2 demo ',  'empty' => 'Seleccione su usuario',  'style' => 'width: 80%;')); ?>

    <?php echo BsHtml::submitButton('Enviar', array('color' => BsHtml::BUTTON_COLOR_PRIMARY)); ?>

<?php $this->endWidget(); ?>

protected/views/formulario/_search.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */
/* @var $form BSActiveForm */
?>

<?php $form=$this->beginWidget('bootstrap.widgets.BsActiveForm', array(
    'action'=>Yii::app()->createUrl($this->route),
    'method'=>'get',
)); ?>

    <?php echo $form->textFieldControlGroup($model,'id',array('maxlength'=>11)); ?>
    <?php echo $form->textFieldControlGroup($model,'nombres',array('maxlength'=>100)); ?>
    <?php echo $form->textFieldControlGroup($model,'apellidos',array('maxlength'=>100)); ?>
    <?php echo $form->textFieldControlGroup($model,'telefono',array('maxlength'=>20)); ?>
    <?php echo $form->textFieldControlGroup($model,'fecha_nacimiento',array('maxlength'=>255)); ?>
    <?php echo $form->textFieldControlGroup($model,'user_id'); ?>

    <div class="form-actions">
        <?php echo BsHtml::submitButton('Buscar',  array('color' => BsHtml::BUTTON_COLOR_PRIMARY,));?>
    </div>

<?php $this->endWidget(); ?>

protected/views/formulario/_view.php
<?php
/* @var $this FormularioController */
/* @var $data Formulario */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id),array('view','id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombres')); ?>:</b>
	<?php echo CHtml::encode($data->nombres); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('apellidos')); ?>:</b>
	<?php echo CHtml::encode($data->apellidos); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('telefono')); ?>:</b>
	<?php echo CHtml::encode($data->telefono); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('fecha_nacimiento')); ?>:</b>
	<?php echo CHtml::encode($data->fecha_nacimiento); ?>
	<br />



	<b><?php echo CHtml::encode($data->getAttributeLabel('user_id')); ?>:</b>
	<?php echo CHtml::encode($data->user_id); ?>
	<br />


</div>

protected/views/formulario/admin.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */


$this->breadcrumbs=array(
	'Formularios'=>array('index'),
	'Administrar',
);

$this->menu=array(
	array('icon' => 'glyphicon glyphicon-list','label'=>'Listar Formulario', 'url'=>array('index')),
	array('icon' => 'glyphicon glyphicon-plus-sign','label'=>'Crear Formulario', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#formulario-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<?php echo BsHtml::pageHeader('Administrar','Formularios') ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo BsHtml::button('Búsqueda avanzada',array('class' =>'search-button', 'icon' => BsHtml::GLYPHICON_SEARCH,'color' => BsHtml::BUTTON_COLOR_PRIMARY), '#'); ?></h3>
    </div>
    <div class="panel-body">
        <p>
            Opcionalmente puede ingresar operadores de comparación (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>
                &lt;&gt;</b>
            ó <b>=</b>) al inicio de cada uno de los valores de búsqueda para especificar cómo debe hacerse la comparación.
        </p>

        <div class="search-form" style="display:none">
            <?php $this->renderPartial('_search',array(
                'model'=>$model,
            )); ?>
        </div>
        <!-- search-form -->

        <?php $this->widget('bootstrap.widgets.BsGridView',array(
			'id'=>'formulario-grid',
			'dataProvider'=>$model->search(),
			'filter'=>$model,
			'columns'=>array(
        		'id',
		'nombres',
		'apellidos',
		'telefono',
		'fecha_nacimiento',
		/*
		'user_id',
		*/
				array(
					'class'=>'bootstrap.widgets.BsButtonColumn',
				),
			),
        )); ?>
    </div>
</div>

protected/views/formulario/create.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */
?>

<?php
$this->breadcrumbs=array(
	'Formularios'=>array('index'),
	'Crear',
);

$this->menu=array(
    array('icon' => 'glyphicon glyphicon-list','label'=>'Listar Formulario', 'url'=>array('index')),
	array('icon' => 'glyphicon glyphicon-tasks','label'=>'Administrar Formulario', 'url'=>array('admin')),
);
?>

<?php echo BsHtml::pageHeader('Crear','Formulario') ?>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/formulario/index.php
<?php
/* @var $this FormularioController */
/* @var $dataProvider CActiveDataProvider */
?>

<?php
$this->breadcrumbs=array(
	'Formularios',
);

$this->menu=array(
    array('icon' => 'glyphicon glyphicon-plus-sign','label'=>'Crear Formulario', 'url'=>array('create')),
    array('icon' => 'glyphicon glyphicon-tasks','label'=>'Administrar Formulario', 'url'=>array('admin')),
);
?>

<?php echo BsHtml::pageHeader('Formularios') ?>
<?php $this->widget('bootstrap.widgets.BsListView',array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

protected/views/formulario/update.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */
?>

<?php
$this->breadcrumbs=array(
	'Formularios'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Editar',
);

$this->menu=array(
    array('icon' => 'glyphicon glyphicon-list','label'=>'Listar Formulario', 'url'=>array('index')),
	array('icon' => 'glyphicon glyphicon-plus-sign','label'=>'Crear Formulario', 'url'=>array('create')),
    array('icon' => 'glyphicon glyphicon-list-alt','label'=>'Detalles Formulario', 'url'=>array('view', 'id'=>$model->id)),
    array('icon' => 'glyphicon glyphicon-tasks','label'=>'Administrar Formulario', 'url'=>array('admin')),
);
?>

<?php echo BsHtml::pageHeader('Editar','Formulario '.$model->id) ?>
<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/formulario/view.php
<?php
/* @var $this FormularioController */
/* @var $model Formulario */
?>

<?php
$this->breadcrumbs=array(
	'Formularios'=>array('index'),
	$model->id,
);

$this->menu=array(
    array('icon' => 'glyphicon glyphicon-list','label'=>'Listar Formulario', 'url'=>array('index')),
	array('icon' => 'glyphicon glyphicon-plus-sign','label'=>'Crear Formulario', 'url'=>array('create')),
	array('icon' => 'glyphicon glyphicon-edit','label'=>'Editar Formulario', 'url'=>array('update', 'id'=>$model->id)),
	array('icon' => 'glyphicon glyphicon-minus-sign','label'=>'Eliminar Formulario', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'¿Está seguro de eliminar este ítem?')),
    array('icon' => 'glyphicon glyphicon-tasks','label'=>'Administrar Formulario', 'url'=>array('admin')),
);
?>
<p>Correo enviado Correctamente</p>
<?php echo BsHtml::pageHeader('Detalles','Formulario '.$model->id) ?>

<?php $this->widget('zii.widgets.CDetailView',array(
	'htmlOptions' => array(
		'class' => 'table table-striped table-condensed table-hover',
	),
	'data'=>$model,
	'attributes'=>array(
		'id',
		'nombres',
		'apellidos',
		'telefono',
		'fecha_nacimiento',
	),
)); ?>